//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.StockHistories = new HashSet<StockHistory>();
        }
    
        public int StockID { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> QuantityRecieved { get; set; }
        public Nullable<decimal> TotalPriceOfItems { get; set; }
        public string QuantityRemainig { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<decimal> perPieceItemPrice { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockHistory> StockHistories { get; set; }
    }
}
